# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\GitHub_Project\ERIC_WORKSPACE\terminal_detect_recognize\inspection_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 458)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 458))
        MainWindow.setMaximumSize(QtCore.QSize(500, 458))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(77, 0))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(300, 0))
        self.label_4.setStyleSheet("border:1px solid black;\n"
"background:white;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 4, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(77, 0))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(77, 0))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actions = QtWidgets.QAction(MainWindow)
        self.actions.setObjectName("actions")
        self.actiondetect = QtWidgets.QAction(MainWindow)
        self.actiondetect.setObjectName("actiondetect")
        self.actionrecognize = QtWidgets.QAction(MainWindow)
        self.actionrecognize.setObjectName("actionrecognize")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "二次回路自动识别"))
        self.pushButton.setStatusTip(_translate("MainWindow", "现场检验人员登录。"))
        self.pushButton.setText(_translate("MainWindow", "用户登录"))
        self.pushButton_3.setStatusTip(_translate("MainWindow", "与远程管理系统通信，识别端子排图片。"))
        self.pushButton_3.setText(_translate("MainWindow", "开始识别"))
        self.pushButton_2.setStatusTip(_translate("MainWindow", "选择待识别端子排图片。"))
        self.pushButton_2.setText(_translate("MainWindow", "选择图片"))
        self.actions.setText(_translate("MainWindow", "程序设置(&P)"))
        self.actions.setIconText(_translate("MainWindow", "软件设置(P)"))
        self.actions.setStatusTip(_translate("MainWindow", "设置本软件运行时的相关参数。"))
        self.actions.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actiondetect.setText(_translate("MainWindow", "检测设置(&D)"))
        self.actiondetect.setStatusTip(_translate("MainWindow", "设置检测端子及铭牌功能的相关参数。"))
        self.actiondetect.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionrecognize.setText(_translate("MainWindow", "识别设置(&R)"))
        self.actionrecognize.setStatusTip(_translate("MainWindow", "设置识别端子及铭牌文本功能的相关参数。"))
        self.actionrecognize.setShortcut(_translate("MainWindow", "Ctrl+R"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
